
engines:
    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php"
            standard: "PSR1,PSR2"
            ignore_warnings: true
        checks:
            Generic Files LineLength TooLong:
                enabled: false
    phpmd:
        enabled: false
        config:
            file_extensions: "php"
            rulesets: "cleancode,codesize,controversial,design,naming,unusedcode"
exclude_paths:
    - "tests/"
    - "!**.php"
