engines:
    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php"
            standard: "PSR1,PSR2"
        checks:
            Generic Files LineLength TooLong:
                enabled: false
            Squiz WhiteSpace SuperfluousWhitespace EndLine:
                enabled: false
    phpmd:
        enabled: true
        config:
            file_extensions: "php"
            rulesets: "controversial,design,naming,unusedcode" # "cleancode,codesize,controversial,design,naming,unusedcode"
        checks:
            Controversial/CamelCaseParameterName:
                enabled: false
            Controversial/CamelCaseVariableName:
                enabled: false
            Naming/ShortMethodName:
                enabled: false
            Naming/ShortVariable:
                enabled: false
            UnusedFormalParameter:
                enabled: false
            UnusedLocalVariable:
                enabled: false
ratings:
    paths:
        - "src/"
exclude_paths:
    - "tests/"
